language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

matrix:
    include:
        # Use precise for PHP 5.3
        - php: 5.3
          dist: precise
        # Test against lowest bounds of dependencies to ensure they are right
        - php: 5.6
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        # Test against dev versions of dependencies
        - php: 5.6
          env: deps=dev
        # test the latest release (including beta releases)
        - php: 7.1
          env: deps=beta

before_install:
    - if [ "$deps" = 'beta' ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;
    - if [ "$deps" = 'dev' ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install:
    - composer update $COMPOSER_FLAGS

script: phpunit --coverage-text

notifications:
    email:
        - travis@knplabs.com
