language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm-nightly

matrix:
    allow_failures:
        - php: 5.6
        - php: hhvm-nightly

env:
    - SYMFONY_VERSION=2.1.*

before_script:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}
    - composer install

script: phpunit --coverage-text

notifications:
    email:
        - travis@knplabs.com
